import Image from 'next/image';
import Link from 'next/link';
import Navbar from '@/components/navbar/Navbar';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Exciting Football Matches',
  description: 'Generated by create next app',
  keywords: ['football'],
  icons: {
    icon: '/ball-football-icon.svg',
  },
};

const Blog = () => {
  const blogData = [
    {
      id: 1,
      title: 'The Excitement of Football Matches',
      date: 'July 15, 2022',
      image: '/photo-1616514169928-a1e40c6f791c.avif',
      slug: 'the-excitement-of-football-matches',
    },
    {
      id: 2,
      title: 'Top Players to Watch This Season',
      date: 'July 20, 2022',
      image: '/istockphoto-992892836-612x612.jpg',
      slug: 'top-players-to-watch-this-season',
    },
    // Add more blog entries as needed
  ];

  return (
    <>
      <main className="min-h-screen">
        {/* Hero section */}
        <Navbar />
        <div className="container max-w-[1000px] mx-auto px-3 lg:px-0 mt-8">
          <h1 className="text-3xl font-bold text-green-500 mb-4">Latest Blog Posts</h1>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {blogData.map((blog) => (
              <Link key={blog.id} href={`/blog/${blog.slug}`}>
                <div>
                  <div className="card p-4 hover:bg-gray-100 transition-all rounded-md">
                    <div className="image-container relative h-48 overflow-hidden rounded-md mb-4">
                      <Image
                        src={blog.image}
                        alt={blog.title}
                        layout="fill"
                        objectFit="cover"
                      />
                    </div>
                    <h2 className="text-xl font-bold text-black">{blog.title}</h2>
                    <p className="text-gray-500">{blog.date}</p>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Blog;
