import Image from 'next/image';
import Link from 'next/link';
import Navbar from '@/components/navbar/Navbar';
import { Metadata } from 'next';
import PageHero from '@/components/PageHero';
import { BlogCard } from '@/components/cards/BlogCard';

export const metadata: Metadata = {
  title: 'Exciting Football Matches',
  description: 'Generated by create next app',
  keywords: ['football'],
  icons: {
    icon: '/ball-football-icon.svg',
  },
};

const Blog = () => {
  const blogData = [
    {
      id: 1,
      title: 'The Excitement of Football Matches',
      date: 'July 15, 2022',
      image: '/photo-1616514169928-a1e40c6f791c.avif',
      slug: 'the-excitement-of-football-matches',
    },
    {
      id: 2,
      title: 'Top Players to Watch This Season',
      date: 'July 20, 2022',
      image: '/istockphoto-992892836-612x612.jpg',
      slug: 'top-players-to-watch-this-season',
    },
    // Add more blog entries as needed
  ];

  return (
    <>
      <main className="min-h-screen">
        {/* Hero section */}
        <Navbar />
        <PageHero
          title="Latest Blog Posts"
          description="Explore our latest blog posts and stay updated on the excitement of football matches."
        />
        <div className="container max-w-[1000px] mx-auto px-3 lg:px-0 mt-8">
          <h1 className="text-3xl font-bold text-green-500 mb-4">Latest Blog Posts</h1>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {blogData.map((blog) => (
              <Link key={blog.id} href={`/blog/${blog.slug}`}>
                <BlogCard
                  title={blog.title}
                  date={blog.date}
                  image={blog.image}
                  alt={`Image for ${blog.title}`}
                />
              </Link>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Blog;