import React from 'react';
import Navbar from '@/components/navbar/Navbar';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Exciting Football Matches',
    description: 'Generated by create next app',
    keywords: ['football'],
    icons: {
      icon: '/ball-football-icon.svg',
    },
  };

const TermsOfService = () => {
  return (
    <main className="min-h-screen">
      <Navbar />
      <div className="container max-w-[800px] mx-auto px-4 lg:px-0 mt-8">
        <h1 className="text-4xl font-bold mb-6">Terms of Service</h1>
        <p className="mb-4">
          Welcome to Exciting Football Matches! These terms and conditions outline the rules and regulations for the use of our website.
        </p>
        <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
        <p className="mb-4">
          By accessing this website, you agree to be bound by these terms of service, all applicable laws, and regulations, and agree that you are responsible for compliance with any applicable local laws.
        </p>
        {/* Add more sections as needed */}
        <h2 className="text-2xl font-bold mb-4">2. User Content</h2>
        <p className="mb-4">
          Our website allows users to submit, post, and share content. You are solely responsible for the content you submit.
        </p>
        <h2 className="text-2xl font-bold mb-4">3. Changes to Terms</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these terms at any time. It is your responsibility to check the terms periodically for changes.
        </p>
      </div>
    </main>
  );
};

export default TermsOfService;