import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ProgressLoding from '@/components/ProgressBar'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Exciting Football Matches',
  description: 'Generated by create next app',
  keywords: ['football'],
  icons: {
    icon: '/ball-football-icon.svg'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.className} min-h-screen`}>
        <ProgressLoding>
          {children}
        </ProgressLoding>
        <Footer />
      </body>
    </html>
  )
}