import Image from 'next/image';
import Link from 'next/link';
import Navbar from '@/components/navbar/Navbar';
import { Metadata } from 'next';
import PageHero from '@/components/PageHero';

export const metadata: Metadata = {
  title: 'Exciting Football Matches',
  description: 'Generated by create next app',
  keywords: ['football'],
  icons: {
    icon: '/ball-football-icon.svg'
  }
}

const ContactUs = () => {
  return (
    <>
      <main className='min-h-screen'>
        {/* Hero section */}
        <Navbar />
        <PageHero
          title="Get in Touch With Us"
          description="We'd love to hear from you!"
        />
        <div className="bg-green-900 text-white">
          <div className='container max-w-[1000px] mx-auto px-3 lg:px-0 py-16'>
            <div className="text-center">
              <h1 className='text-4xl lg:text-6xl font-bold mb-4'>Get in Touch With Us</h1>
              <p className='text-xl mb-8'>We'd love to hear from you!</p>
              {/* Contact Form */}
              <form className='max-w-md mx-auto'>
                <div className='mb-4'>
                  <label htmlFor='name' className='text-lg'>Your Name</label>
                  <input type='text' id='name' name='name' className='w-full p-2 border rounded focus:outline-none focus:ring input input-info' />
                </div>
                <div className='mb-4'>
                  <label htmlFor='email' className='text-lg'>Your Email</label>
                  <input type='email' id='email' name='email' className='w-full p-2 border rounded focus:outline-none focus:ring input input-info' />
                </div>
                <div className='mb-4'>
                  <label htmlFor='message' className='text-lg'>Your Message</label>
                  <textarea id='message' name='message' rows={4} className='w-full p-2 border rounded focus:outline-none text-black focus:ring focus:border-green-500 textarea textarea-info'></textarea>
                </div>
                <button type='submit' className='bg-white text-green-900 py-2 px-6 rounded-full text-lg font-semibold hover:bg-green-500 hover:text-white transition-all duration-300'>
                  Send Message
                </button>
              </form>
              {/* Additional Details */}
              <div className='mt-12'>
                <p className='text-lg'>
                  If you prefer, you can also reach us via email at <span className='font-semibold'>info@excitingfootballmatches.com</span>.
                </p>
                <p className='text-lg mt-4'>
                  Our office is located at <span className='font-semibold'>123 Football Street, Stadium City</span>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

export default ContactUs;