import Image from 'next/image';
import Link from 'next/link';
import Navbar from '@/components/navbar/Navbar';
import { Metadata } from 'next';
import PageHero from '@/components/PageHero';
import { BlogCard } from '@/components/cards/BlogCard';

export const metadata: Metadata = {
  title: 'Exciting Football Matches',
  description: 'Generated by create next app',
  keywords: ['football'],
  icons: {
    icon: '/ball-football-icon.svg',
  },
};

const formatDate = (dateString: string): string => {
  const options = { year: 'numeric', month: 'short', day: 'numeric' };
  return new Date(dateString).toLocaleDateString('en-US', options as any);
};

const Blog = async () => {
  const apiDat = await fetch('https://blog.crackstreamsports.live/wp-json/wp/v2/posts');
  const data = await apiDat.json();

  // console.log(data);

  const blogData = data.map((blog: any) => ({
    id: blog.id,
    title: blog.title.rendered,
    date: formatDate(blog.date),
    image: blog.featured_media
      ? blog._embedded['wp:featuredmedia'][0].source_url
      : '/image-placeholder.png',
    slug: blog.slug,
  }));

  return (
    <>
      <main className="min-h-screen">
        {/* Hero section */}
        <Navbar />
        {/* Top Google Ads */}
        <div className="text-center mb-4">
          {/* Insert Google Ads code or component here */}
          {/* Example: <GoogleAdsComponent /> */}
          <div className="container mx-auto">
            <h1>Top Google Ads</h1>
          </div>
        </div>
        <PageHero
          title="Latest Blog Posts"
          description="Explore our latest blog posts and stay updated on the excitement of football matches."
        />
        <div className="container max-w-[1000px] mx-auto px-3 lg:px-0 mt-8">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
            {blogData.map((blog:any) => (
              <Link key={blog.id} href={`/blog/${blog.slug}`}>
                <BlogCard
                  title={blog.title}
                  date={blog.date}
                  image={blog.image}
                  alt={`Image for ${blog.title}`}
                />
              </Link>
            ))}
          </div>
        </div>
        {/* Space for Google Ads */}
        <div className="container mx-auto max-w-[1000px] my-8 px-3 lg:px-0">
          {/* Insert Google Ads code or component here */}
          Show: GoogleAds
        </div>
      </main>
    </>
  );
};

export default Blog;